# yaml-language-server: $schema=https://github.com/Informatiqal/publiqate/blob/main/schemas/config.json?raw=true

general:
  port: 8000
  uri: "192.168.0.1"
  # certs: ${notifications_certs}
  logLevel: info
  vars: "./vars.txt"
  admin:
    # port: 8001
    cookie:
      name: ${cookie_name}
      value: ${cookie_value}
    certs: ${admin_certs}

qlik:
  - name: QS Dev
    certs: ${qlik_cert}
    host: ${central_node}
    userName: ${qlik_user}
    userDir: ${qlik_user_dir}

plugins:
  - ${plugins_path}\my-plugin\index.js

notifications:
  - name: All failed tasks
    type: ExecutionResult
    environment: QS Dev
    id: 999999999-8888-7777-6666-55555555555
    filter: status eq 8 # 8 -> FinishedFail
    changeType: update # add, update or delete
    options:
      disableCors: true
      whitelist:
        - ${source_whitelist_1}
        - ${source_whitelist_2}
      enabled: false # notifications can be disabled if needed
      getEntityDetails: true # if "true" include the entity details within the event. Default is true 
    callback:
      # http plugin is built-in
      - type: http
        details:
          method: post # get, post, put or delete
          url: http://localhost:3000 # where to send the event

  - name: Get specific stream updates
    type: Stream
    environment: QS Dev
    id: 111111111-2222-3333-4444-55555555555
    filter: name eq 'Some stream name'
    changeType: update
    callback:
      # echo plugin is built-in. It just output to the log file
      - type: echo
        disabled: true # callbacks can be disabled if needed
      - type: file
        details:
          path: c:\path\to\store\notification\data.json
