/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type GeneralConfig1 = number;
export type GeneralConfig2 = string;
export type GeneralConfig3 = string;
export type GeneralConfig4 = GeneralConfig5 | GeneralConfig6;
export type GeneralConfig5 = "debug" | "info" | "error";
export type GeneralConfig7 = "debug" | "info" | "error";
export type GeneralConfig8 = "debug" | "info" | "error";
export type GeneralConfig9 = "debug" | "info" | "error";
export type GeneralConfig10 = "debug" | "info" | "error";
export type GeneralConfig11 = GeneralConfig12 | GeneralConfig13;
/**
 * Location to file where secrets are stored
 */
export type GeneralConfig12 = string;
/**
 * Location to file where secrets are stored
 */
export type GeneralConfig14 = string;
/**
 * Locations of files where the secrets are stored. Files are loaded alphabetically and last variable occurrence becomes the active one
 */
export type GeneralConfig13 = GeneralConfig14[];
export type GeneralConfig16 = boolean;
export type GeneralConfig17 = boolean;
export type GeneralConfig18 = boolean;
export type GeneralConfig19 = boolean;
export type GeneralConfig20 = GeneralConfig21 | GeneralConfig27;
export type GeneralConfig23 = string;
export type GeneralConfig24 = string;
export type GeneralConfig25 = string;
export type GeneralConfig26 = number;
export type GeneralConfig27 = boolean;
export type GeneralConfig29 = string;
export type GeneralConfig28 = GeneralConfig29[];
export type GeneralConfig31 = boolean;
export type GeneralConfig32 = boolean;
/**
 * Basic regex to allow urls only (to avoid any further issues as earlier as possible)
 */
export type GeneralConfig34 = string;
export type GeneralConfig33 = GeneralConfig34[];

/**
 * Publiqate config JSON schema (@informatiqal)
 */
export interface GeneralConfig {
  port: GeneralConfig1;
  uri: GeneralConfig2;
  certs?: GeneralConfig3;
  logLevel?: GeneralConfig4;
  vars?: GeneralConfig11;
  builtInPlugins?: GeneralConfig15;
  deregisterMissing?: GeneralConfig19;
  admin: GeneralConfig20;
  plugins?: GeneralConfig28;
  notifications?: GeneralConfig30;
  [k: string]: unknown;
}
export interface GeneralConfig6 {
  core: GeneralConfig7;
  admin?: GeneralConfig8;
  qlik?: GeneralConfig9;
  [k: string]: GeneralConfig10;
}
export interface GeneralConfig15 {
  echo?: GeneralConfig16;
  http?: GeneralConfig17;
  file?: GeneralConfig18;
  [k: string]: unknown;
}
export interface GeneralConfig21 {
  cookie: GeneralConfig22;
  certs: GeneralConfig25;
  port?: GeneralConfig26;
}
export interface GeneralConfig22 {
  name: GeneralConfig23;
  value: GeneralConfig24;
  [k: string]: unknown;
}
export interface GeneralConfig30 {
  getEntityDetails?: GeneralConfig31;
  disableCors?: GeneralConfig32;
  whitelist?: GeneralConfig33;
}
