/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NotificationsConfig1 = NotificationsConfig2 | NotificationsConfig20;
export type NotificationsConfig3 =
  | "App"
  | "AnalyticConnection"
  | "ContentLibrary"
  | "DataConnection"
  | "Extension"
  | "ExecutionResult"
  | "ReloadTask"
  | "Stream"
  | "User"
  | "UserSyncTask"
  | "SystemRule"
  | "Tag"
  | "CustomPropertyDefinition"
  | "EngineService"
  | "OdagService"
  | "PrintingService"
  | "ProxyService"
  | "RepositoryService"
  | "SchedulerService"
  | "ServerNodeConfiguration"
  | "VirtualProxyConfig";
export type NotificationsConfig4 = string;
/**
 * MANDATORY. Name of the notification. Must be unique. Must be unique across all notifications.
 */
export type NotificationsConfig5 = string;
export type NotificationsConfig6 = "add" | "update" | "delete";
export type NotificationsConfig7 = string;
export type NotificationsConfig8 = string;
export type NotificationsConfig9 = string;
export type NotificationsConfig10 = string;
export type NotificationsConfig12 = boolean;
export type NotificationsConfig13 = boolean;
export type NotificationsConfig14 = boolean;
export type NotificationsConfig16 = string;
export type NotificationsConfig15 = NotificationsConfig16[];
export type NotificationsConfig19 = string;
export type NotificationsConfig17 = NotificationsConfig18[];
export type NotificationsConfig21 = "DataAlert";
export type NotificationsConfig22 = string;
/**
 * MANDATORY. Name of the notification. Must be unique across all notifications.
 */
export type NotificationsConfig23 = string;
export type NotificationsConfig24 = string;
export type NotificationsConfig25 = string;
/**
 * @minItems 1
 */
export type NotificationsConfig26 = [NotificationsConfig27, ...NotificationsConfig27[]];
export type NotificationsConfig29 = NotificationsConfig30 | NotificationsConfig37;
export type NotificationsConfig31 = string;
export type NotificationsConfig32 = string;
export type NotificationsConfig34 = NotificationsConfig35 | NotificationsConfig36;
export type NotificationsConfig35 = string;
export type NotificationsConfig36 = number;
export type NotificationsConfig33 = NotificationsConfig34[];
export type NotificationsConfig38 = NotificationsConfig39 | NotificationsConfig40;
export type NotificationsConfig39 = string;
export type NotificationsConfig40 = number;
export type NotificationsConfig28 = NotificationsConfig29[];
export type NotificationsConfig42 = NotificationsConfig43 | NotificationsConfig51;
export type NotificationsConfig44 = string;
export type NotificationsConfig45 = string;
export type NotificationsConfig46 = "list";
export type NotificationsConfig47 = string;
export type NotificationsConfig49 = string;
export type NotificationsConfig48 = NotificationsConfig49[];
export type NotificationsConfig50 = "present" | "missing";
export type NotificationsConfig52 = string;
export type NotificationsConfig53 = string;
export type NotificationsConfig54 = "scalar";
export type NotificationsConfig55 = string;
/**
 * @minItems 1
 */
export type NotificationsConfig56 = [NotificationsConfig57, ...NotificationsConfig57[]];
export type NotificationsConfig57 = NotificationsConfig58 | NotificationsConfig65;
export type NotificationsConfig58 = NotificationsConfig59 | NotificationsConfig63;
export type NotificationsConfig60 = NotificationsConfig61 | NotificationsConfig62;
export type NotificationsConfig61 = string;
export type NotificationsConfig62 = number;
export type NotificationsConfig64 = string;
export type NotificationsConfig65 = NotificationsConfig66 | NotificationsConfig71;
export type NotificationsConfig66 = NotificationsConfig67 & NotificationsConfig68;
export type NotificationsConfig67 = NotificationsConfig59 | NotificationsConfig63;
export type NotificationsConfig69 = "<" | ">" | ">=" | "<=" | "==" | "!=" | "=" | "<>";
export type NotificationsConfig70 = string;
export type NotificationsConfig71 = NotificationsConfig67 & NotificationsConfig72;
export type NotificationsConfig73 = string;
export type NotificationsConfig74 = string;
export type NotificationsConfig75 = string;
export type NotificationsConfig76 = NotificationsConfig77 | NotificationsConfig82 | NotificationsConfig86;
export type NotificationsConfig77 = NotificationsConfig78 | NotificationsConfig80;
export type NotificationsConfig79 = boolean;
export type NotificationsConfig81 = boolean;
export type NotificationsConfig82 = NotificationsConfig83 & NotificationsConfig84;
export type NotificationsConfig83 = NotificationsConfig78 | NotificationsConfig80;
export type NotificationsConfig85 = string;
export type NotificationsConfig87 = string;
export type NotificationsConfig41 = NotificationsConfig42[];
export type NotificationsConfig89 = string;
export type NotificationsConfig91 = boolean;
export type NotificationsConfig92 = boolean;
export type NotificationsConfig93 = boolean;
export type NotificationsConfig95 = string;
export type NotificationsConfig94 = NotificationsConfig95[];
export type NotificationsConfig96 = string;
export type NotificationsConfig99 = string;
export type NotificationsConfig97 = NotificationsConfig98[];
/**
 * Publiqate config JSON schema (@informatiqal)
 */
export type NotificationsConfig = NotificationsConfig1[];

export interface NotificationsConfig2 {
  type: NotificationsConfig3;
  environment: NotificationsConfig4;
  name: NotificationsConfig5;
  changeType: NotificationsConfig6;
  filter?: NotificationsConfig7;
  condition?: NotificationsConfig8;
  propertyName?: NotificationsConfig9;
  description?: NotificationsConfig10;
  options?: NotificationsConfig11;
  callbacks?: NotificationsConfig17;
}
export interface NotificationsConfig11 {
  getEntityDetails?: NotificationsConfig12;
  disableCors?: NotificationsConfig13;
  enabled?: NotificationsConfig14;
  whitelist?: NotificationsConfig15;
  [k: string]: unknown;
}
export interface NotificationsConfig18 {
  type: NotificationsConfig19;
  [k: string]: unknown;
}
export interface NotificationsConfig20 {
  type: NotificationsConfig21;
  environment: NotificationsConfig22;
  name: NotificationsConfig23;
  filter?: NotificationsConfig24;
  condition?: NotificationsConfig25;
  "data-conditions"?: NotificationsConfig26;
  options?: NotificationsConfig90;
  description?: NotificationsConfig96;
  callbacks?: NotificationsConfig97;
}
export interface NotificationsConfig27 {
  selections: NotificationsConfig28;
  conditions: NotificationsConfig41;
  options?: NotificationsConfig88;
  [k: string]: unknown;
}
export interface NotificationsConfig30 {
  field?: NotificationsConfig31;
  state?: NotificationsConfig32;
  values?: NotificationsConfig33;
}
export interface NotificationsConfig37 {
  bookmark?: NotificationsConfig38;
}
export interface NotificationsConfig43 {
  name: NotificationsConfig44;
  description?: NotificationsConfig45;
  type: NotificationsConfig46;
  fieldName: NotificationsConfig47;
  values: NotificationsConfig48;
  operation: NotificationsConfig50;
}
export interface NotificationsConfig51 {
  name: NotificationsConfig52;
  description?: NotificationsConfig53;
  type: NotificationsConfig54;
  expression: NotificationsConfig55;
  results: NotificationsConfig56;
}
export interface NotificationsConfig59 {
  value: NotificationsConfig60;
  [k: string]: unknown;
}
export interface NotificationsConfig63 {
  expression: NotificationsConfig64;
  [k: string]: unknown;
}
export interface NotificationsConfig68 {
  operator?: NotificationsConfig69;
  variation?: NotificationsConfig70;
}
export interface NotificationsConfig72 {
  startsWith?: NotificationsConfig73;
  endsWith?: NotificationsConfig74;
  subStringOf?: NotificationsConfig75;
  options?: NotificationsConfig76;
  [k: string]: unknown;
}
export interface NotificationsConfig78 {
  toLower: NotificationsConfig79;
  [k: string]: unknown;
}
export interface NotificationsConfig80 {
  toUpper: NotificationsConfig81;
  [k: string]: unknown;
}
export interface NotificationsConfig84 {
  test?: NotificationsConfig85;
  [k: string]: unknown;
}
export interface NotificationsConfig86 {
  test?: NotificationsConfig87;
  [k: string]: unknown;
}
export interface NotificationsConfig88 {
  user?: NotificationsConfig89;
  [k: string]: unknown;
}
export interface NotificationsConfig90 {
  getEntityDetails?: NotificationsConfig91;
  disableCors?: NotificationsConfig92;
  enabled?: NotificationsConfig93;
  whitelist?: NotificationsConfig94;
  [k: string]: unknown;
}
export interface NotificationsConfig98 {
  type: NotificationsConfig99;
  [k: string]: unknown;
}
