/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Publiqate config JSON schema (@informatiqal)
 *
 * @minItems 1
 */
export type QlikConfig = [QlikConfig1, ...QlikConfig1[]];
/**
 * User defined name of the Qlik environment
 */
export type QlikConfig2 = string;
/**
 * Path to folder where the Qlik certificates are stored
 */
export type QlikConfig3 = string;
export type QlikConfig4 = string;
export type QlikConfig5 = string;
export type QlikConfig6 = string;

export interface QlikConfig1 {
  name: QlikConfig2;
  certs: QlikConfig3;
  host: QlikConfig4;
  userName?: QlikConfig5;
  userDir?: QlikConfig6;
}
